<?php


namespace App\Views;

use App\App;
use Core\View;

class Navigation extends View
{
    public function render($template_path = ROOT . '/app/templates/navigation.tpl.php')
    {
        return parent::render($template_path); // TODO: Change the autogenerated stub
    }

    public function __construct()
    {
        parent::__construct($this->generate());
    }

    public function generate()
    {
        $nav = ['/index.php' => 'Home'];
        if (App::$session->getUser()) {
            return $nav + [
                    '/admin/add.php' => 'Add',
                    '/logout.php' => 'Logout',
                ];
        } else {
            return $nav + [
                    '/register.php' => 'Register',
                    '/login.php' => 'Login',
                ];
        }

    }

}
